[package]
name = "cadence"
version = "0.1.0-beta.1"
edition = "2021"
authors = ["Darshan Heble <darshanheble@github.com>"]
description = "Automated Git progress pacing system written in Rust with TUI & CLI"
readme = "README.md"
repository = "https://github.com/DarshanHeble/cadence"
license = "MIT OR Apache-2.0"
keywords = ["git", "pacing", "tui", "cli", "github"]
categories = ["command-line-utilities", "development-tools"]


[[bin]]
name = "cadence"
path = "src/main.rs"

[[bin]]
name = "cad"
path = "src/bin/cad.rs"


[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.8"
ratatui = "0.26"
crossterm = "0.27"
regex = "1.10"
